branches:
  only:
  - master

before_install:
  - openssl aes-256-cbc -K $encrypted_6afd0fc9428e_key -iv $encrypted_6afd0fc9428e_iv -in secring.gpg.enc -out secring.gpg -d
  - gpg --import secring.gpg
  - export SECRING_FILE="$PWD/secring.gpg"

install:
  - ./gradlew publish